services:
  notify-service:
    container_name: notify-service
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - notify-service:/app
    ports:
      - "7002:8000"

volumes:
  notify-service:
